# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 76d81c8363b80228f160688b42355bc6de778476bcda6ada11ca00d578702d5e720a835e5c08e60a16a2e57f2c97be488c1eef0852ff0064592b48d711313dac

test:
  secret_key_base: 87680a34162b6646fbc9da653caf3f702a679bfac94a3351d1ed2bccc6599fc744d07c4a7e931dd8afe2e29bde38c68d8b5470704b12eeb47e864f17a971b871

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
